export const categories = [
  {
    id: 'braking',
    name: 'Brakes & Rotors',
    short: 'Brakes',
    desc: 'Pads, discs, drums and complete brake kits',
    icon: 'braking',
  },
  {
    id: 'filters',
    name: 'Filters & Fluids',
    short: 'Filters',
    desc: 'Air, oil, fuel and cabin filters',
    icon: 'filters',
  },
  {
    id: 'engine',
    name: 'Engine Parts',
    short: 'Engine',
    desc: 'Clutch kits, belts, plugs & timing components',
    icon: 'engine',
  },
  {
    id: 'suspension',
    name: 'Suspension & Steering',
    short: 'Suspension',
    desc: 'Shocks, arms, bushings and tie rods',
    icon: 'suspension',
  },
  {
    id: 'electrical',
    name: 'Electrical & Sensors',
    short: 'Electrical',
    desc: 'Batteries, bulbs, sensors and alternators',
    icon: 'electrical',
  },
  {
    id: 'cooling',
    name: 'Cooling & Radiators',
    short: 'Cooling',
    desc: 'Radiators, fans, thermostats and hoses',
    icon: 'cooling',
  },
  {
    id: 'transmission',
    name: 'Transmission & Clutch',
    short: 'Transmission',
    desc: 'Clutch plates, flywheels and gearbox parts',
    icon: 'transmission',
  },
  {
    id: 'care',
    name: 'Car Care & Accessories',
    short: 'Car Care',
    desc: 'Polishes, mats, covers and detailing gear',
    icon: 'care',
  },
]

export const vehicles = [
  { id: 'swift', make: 'Maruti Suzuki', model: 'Swift', years: '2018 – 2024', engine: '1.2L K12C' },
  { id: 'baleno', make: 'Maruti Suzuki', model: 'Baleno', years: '2019 – 2024', engine: '1.2L K12N' },
  { id: 'dzire', make: 'Maruti Suzuki', model: 'Dzire', years: '2017 – 2024', engine: '1.2L K12N' },
  { id: 'wagonr', make: 'Maruti Suzuki', model: 'WagonR', years: '2019 – 2024', engine: '1.0L K10C' },
  { id: 'brezza', make: 'Maruti Suzuki', model: 'Brezza', years: '2020 – 2024', engine: '1.5L K15B' },
  { id: 'ertiga', make: 'Maruti Suzuki', model: 'Ertiga', years: '2018 – 2024', engine: '1.5L K15B' },
  { id: 'ciaz', make: 'Maruti Suzuki', model: 'Ciaz', years: '2018 – 2024', engine: '1.5L K15B' },
  { id: 'alto', make: 'Maruti Suzuki', model: 'Alto K10', years: '2019 – 2024', engine: '1.0L K10C' },
  { id: 'jimny', make: 'Maruti Suzuki', model: 'Jimny', years: '2023 – 2024', engine: '1.5L K15B' },
  { id: 'fronx', make: 'Maruti Suzuki', model: 'Fronx', years: '2023 – 2024', engine: '1.2L / 1.0T' },
  { id: 'i20', make: 'Hyundai', model: 'i20', years: '2020 – 2024', engine: '1.2L / 1.0T' },
  { id: 'creta', make: 'Hyundai', model: 'Creta', years: '2020 – 2024', engine: '1.5L NA / 1.5T' },
  { id: 'venue', make: 'Hyundai', model: 'Venue', years: '2019 – 2024', engine: '1.0T / 1.5L' },
  { id: 'verna', make: 'Hyundai', model: 'Verna', years: '2020 – 2024', engine: '1.5 NA / 1.5T' },
  { id: 'aura', make: 'Hyundai', model: 'Aura', years: '2020 – 2024', engine: '1.2L' },
  { id: 'alcazar', make: 'Hyundai', model: 'Alcazar', years: '2021 – 2024', engine: '2.0L / 1.5T' },
  { id: 'i10', make: 'Hyundai', model: 'Grand i10 Nios', years: '2019 – 2024', engine: '1.2L' },
  { id: 'tucson', make: 'Hyundai', model: 'Tucson', years: '2020 – 2024', engine: '2.0L' },
  { id: 'nexon', make: 'Tata', model: 'Nexon', years: '2020 – 2024', engine: '1.2T Revotron' },
  { id: 'punch', make: 'Tata', model: 'Punch', years: '2021 – 2024', engine: '1.2T / 1.2L' },
  { id: 'harrier', make: 'Tata', model: 'Harrier', years: '2019 – 2024', engine: '2.0L Kryotec' },
  { id: 'safari', make: 'Tata', model: 'Safari', years: '2021 – 2024', engine: '2.0L Kryotec' },
  { id: 'tiago', make: 'Tata', model: 'Tiago', years: '2016 – 2024', engine: '1.2L Revotron' },
  { id: 'altroz', make: 'Tata', model: 'Altroz', years: '2020 – 2024', engine: '1.2T / 1.5L' },
  { id: 'tigor', make: 'Tata', model: 'Tigor', years: '2017 – 2024', engine: '1.2L Revotron' },
  { id: 'curvv', make: 'Tata', model: 'Curvv', years: '2024 – 2024', engine: '1.2T / 1.5T' },
  { id: 'xuv700', make: 'Mahindra', model: 'XUV700', years: '2021 – 2024', engine: '2.0T mStallion' },
  { id: 'scorpio', make: 'Mahindra', model: 'Scorpio-N', years: '2022 – 2024', engine: '2.0T / 2.2L' },
  { id: 'thar', make: 'Mahindra', model: 'Thar', years: '2020 – 2024', engine: '2.0T / 2.2L' },
  { id: 'xuv300', make: 'Mahindra', model: 'XUV300', years: '2019 – 2024', engine: '1.2T / 1.5L' },
  { id: 'bolero', make: 'Mahindra', model: 'Bolero', years: '2018 – 2024', engine: '1.5L mHawk' },
  { id: 'innova', make: 'Toyota', model: 'Innova Crysta', years: '2016 – 2024', engine: '2.4L Diesel' },
  { id: 'fortuner', make: 'Toyota', model: 'Fortuner', years: '2017 – 2024', engine: '2.8L Diesel' },
  { id: 'hyryder', make: 'Toyota', model: 'Hyryder', years: '2022 – 2024', engine: '1.5L / Hybrid' },
  { id: 'urban', make: 'Toyota', model: 'Urban Cruiser', years: '2020 – 2024', engine: '1.5L' },
  { id: 'camry', make: 'Toyota', model: 'Camry Hybrid', years: '2020 – 2024', engine: '2.5L Hybrid' },
  { id: 'city', make: 'Honda', model: 'City', years: '2020 – 2024', engine: '1.5L i-VTEC' },
  { id: 'amaze', make: 'Honda', model: 'Amaze', years: '2018 – 2024', engine: '1.2L / 1.5L' },
  { id: 'elevate', make: 'Honda', model: 'Elevate', years: '2023 – 2024', engine: '1.5L i-VTEC' },
  { id: 'seltos', make: 'Kia', model: 'Seltos', years: '2019 – 2024', engine: '1.5L / 1.4T' },
  { id: 'sonet', make: 'Kia', model: 'Sonet', years: '2020 – 2024', engine: '1.2L / 1.0T' },
  { id: 'carens', make: 'Kia', model: 'Carens', years: '2022 – 2024', engine: '1.5L / 1.4T' },
  { id: 'virtus', make: 'Volkswagen', model: 'Virtus', years: '2022 – 2024', engine: '1.0T / 1.5T' },
  { id: 'taigun', make: 'Volkswagen', model: 'Taigun', years: '2021 – 2024', engine: '1.0T / 1.5T' },
  { id: 'slavia', make: 'Skoda', model: 'Slavia', years: '2022 – 2024', engine: '1.0T / 1.5T' },
  { id: 'kushaq', make: 'Skoda', model: 'Kushaq', years: '2021 – 2024', engine: '1.0T / 1.5T' },
  { id: 'kwid', make: 'Renault', model: 'Kwid', years: '2015 – 2024', engine: '0.8L / 1.0L' },
  { id: 'kiger', make: 'Renault', model: 'Kiger', years: '2021 – 2024', engine: '1.0L / 1.0T' },
  { id: 'triber', make: 'Renault', model: 'Triber', years: '2019 – 2024', engine: '1.0L' },
  { id: 'magnite', make: 'Nissan', model: 'Magnite', years: '2020 – 2024', engine: '1.0L / 1.0T' },
  { id: 'hector', make: 'MG', model: 'Hector', years: '2019 – 2024', engine: '1.5T / 2.0L' },
  { id: 'astor', make: 'MG', model: 'Astor', years: '2021 – 2024', engine: '1.3T / 1.5L' },
  { id: 'ecosport', make: 'Ford', model: 'EcoSport', years: '2013 – 2021', engine: '1.5L' },
  { id: 'endeavour', make: 'Ford', model: 'Endeavour', years: '2016 – 2021', engine: '2.0T / 3.2L' },
  { id: 'compass', make: 'Jeep', model: 'Compass', years: '2017 – 2024', engine: '1.4T / 2.0L' },
  { id: 'meridian', make: 'Jeep', model: 'Meridian', years: '2022 – 2024', engine: '2.0L' },
  { id: 'cclass', make: 'Mercedes-Benz', model: 'C-Class', years: '2018 – 2024', engine: '1.5T / 2.0T' },
  { id: 'gla', make: 'Mercedes-Benz', model: 'GLA', years: '2020 – 2024', engine: '1.3T' },
  { id: 'x1', make: 'BMW', model: 'X1', years: '2016 – 2024', engine: '2.0T' },
  { id: 'series3', make: 'BMW', model: '3 Series', years: '2019 – 2024', engine: '2.0T' },
  { id: 'a4', make: 'Audi', model: 'A4', years: '2017 – 2024', engine: '2.0T' },
  { id: 'q3', make: 'Audi', model: 'Q3', years: '2019 – 2024', engine: '1.4T / 2.0T' },
  { id: 'c3', make: 'Citroën', model: 'C3', years: '2022 – 2024', engine: '1.2L / 1.2T' },
]

export const brands = [
  'Bosch',
  'Mann-Filter',
  'NGK',
  'FEBI',
  'Monroe',
  'Hella',
  'Mahle',
  'Kyb',
  'Exide',
  'TVS',
  'Luk',
  'Valeo',
]

const fitsAll = () => vehicles.map((v) => v.id)
const idsByMake = (...makes) => vehicles.filter((v) => makes.includes(v.make)).map((v) => v.id)

export const products = [
  {
    id: 'p1',
    name: 'Ceramic Disc Brake Pad Set (Front)',
    category: 'braking',
    brand: 'Bosch',
    partNo: '0 986 AB1 238',
    price: 1499,
    mrp: 1899,
    stock: 48,
    rating: 4.6,
    reviews: 214,
    popular: true,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Hyundai', 'Tata', 'Honda'),
    desc: 'Low-dust ceramic compound front pads with stainless steel shims. Quieter stops, less brake dust and a longer pad life than standard semi-metallic pads.',
    features: [
      'Ceramic friction compound',
      'Low dust & noise',
      'Fitted with wear sensors',
      'OES specification',
    ],
  },
  {
    id: 'p2',
    name: 'Ventilated Front Disc Rotor 259mm',
    category: 'braking',
    brand: 'FEBI',
    partNo: 'FEBI 18899',
    price: 2399,
    mrp: 2999,
    stock: 0,
    rating: 4.5,
    reviews: 98,
    popular: false,
    badge: 'low',
    fits: idsByMake('Maruti Suzuki', 'Hyundai'),
    desc: 'High-carbon alloy ventilated disc machined to OEM tolerances. Anti-rust coated hub for a cleaner look and longer service life.',
    features: ['High carbon alloy', 'Precision balanced', 'Anti-corrosion coating', 'OEM dimensions'],
  },
  {
    id: 'p3',
    name: 'Complete Brake Kit — Pads + Rotors',
    category: 'braking',
    brand: 'TVS',
    partNo: 'TVS BK-4A',
    price: 4199,
    mrp: 5199,
    stock: 21,
    rating: 4.8,
    reviews: 342,
    popular: true,
    badge: 'top',
    fits: idsByMake('Tata', 'Hyundai', 'Mahindra'),
    desc: 'Everything you need for a full front axle brake job. Matching pads and rotors tuned together for consistent bite and fade resistance.',
    features: ['Pads + rotors combo', 'Fade resistant', 'Includes mounting hardware', 'Balanced pairing'],
  },
  {
    id: 'p4',
    name: 'Premium Cabin Air Filter with Carbon',
    category: 'filters',
    brand: 'Mann-Filter',
    partNo: 'CUK 2434',
    price: 549,
    mrp: 720,
    stock: 140,
    rating: 4.7,
    reviews: 561,
    popular: true,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Hyundai', 'Tata', 'Honda'),
    desc: 'Activated carbon cabin filter that traps pollen, dust and road odours. Keeps the cabin air fresh for up to 15,000 km.',
    features: ['Activated carbon layer', 'HEPA-like media', 'Anti-odour', '12000–15000 km life'],
  },
  {
    id: 'p5',
    name: 'Engine Oil Filter — Spin-on',
    category: 'filters',
    brand: 'Mann-Filter',
    partNo: 'W 712/22',
    price: 399,
    mrp: 499,
    stock: 96,
    rating: 4.8,
    reviews: 738,
    popular: false,
    badge: 'top',
    fits: fitsAll(),
    desc: 'High-efficiency paper element with silicone anti-drain valve. Premium protection for petrol and diesel engines alike.',
    features: ['Silicone anti-drain valve', '99% filtration efficiency', '10,000 km interval', 'Universal fit range'],
  },
  {
    id: 'p6',
    name: 'Air Filter Element — Panel Type',
    category: 'filters',
    brand: 'Mahle',
    partNo: 'LX 1768',
    price: 649,
    mrp: 850,
    stock: 0,
    rating: 4.4,
    reviews: 132,
    popular: false,
    badge: 'low',
    fits: idsByMake('Hyundai', 'Tata', 'Honda'),
    desc: 'Panel-style engine air filter with pleated non-woven media. Protects the engine from dirt, sand and debris.',
    features: ['Pleated media', 'OEM fitment', 'Long service life', 'Best airflow balance'],
  },
  {
    id: 'p7',
    name: 'Full Synthetic Engine Oil 5W-30 (5L)',
    category: 'filters',
    brand: 'Bosch',
    partNo: 'BOS 5W30-5L',
    price: 2799,
    mrp: 3299,
    stock: 60,
    rating: 4.9,
    reviews: 412,
    popular: true,
    badge: null,
    fits: fitsAll(),
    desc: 'Full synthetic 5W-30 engineered for modern petrol engines. Keeps the engine clean and protects from cold-start wear.',
    features: ['Full synthetic', 'API SP / ACEA C3', 'Excellent cold flow', '5 litre pack'],
  },
  {
    id: 'p8',
    name: 'Iridium Spark Plug (Set of 4)',
    category: 'engine',
    brand: 'NGK',
    partNo: 'NGK 96312',
    price: 1899,
    mrp: 2400,
    stock: 34,
    rating: 4.8,
    reviews: 289,
    popular: true,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Hyundai', 'Tata'),
    desc: 'OE-specified laser-welded iridium plugs. Sharper ignition, smoother idle and up to 60,000 km of service life.',
    features: ['Iridium tip', 'Laser welded', '60,000 km life', 'Pre-gapped'],
  },
  {
    id: 'p9',
    name: 'Timing Belt + Tensioner Kit',
    category: 'engine',
    brand: 'Luk',
    partNo: 'LUK 534 0103',
    price: 5499,
    mrp: 6899,
    stock: 0,
    rating: 4.7,
    reviews: 87,
    popular: false,
    badge: 'low',
    fits: idsByMake('Honda', 'Hyundai'),
    desc: 'Complete timing service kit with belt, hydraulic tensioner and idler pulleys. Designed to OEM wear limits.',
    features: ['Belt + tensioner + idler', 'Hydraulic tensioner', 'OEM tolerances', '60,000 km interval'],
  },
  {
    id: 'p10',
    name: 'Poly V Drive Belt (Auxiliary)',
    category: 'engine',
    brand: 'FEBI',
    partNo: 'FEBI 27434',
    price: 899,
    mrp: 1150,
    stock: 55,
    rating: 4.5,
    reviews: 74,
    popular: false,
    badge: null,
    fits: idsByMake('Hyundai', 'Tata', 'Mahindra'),
    desc: 'Reinforced EPDM ribbed belt for alternator, A/C and power steering drives. Quiet, stable and long-wearing.',
    features: ['EPDM compound', 'Quiet operation', 'Anti-crack', 'OE lengths'],
  },
  {
    id: 'p11',
    name: 'Front Shock Absorber — Gas',
    category: 'suspension',
    brand: 'Monroe',
    partNo: 'G16551',
    price: 3299,
    mrp: 4099,
    stock: 18,
    rating: 4.6,
    reviews: 156,
    popular: true,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Hyundai'),
    desc: 'Twin-tube gas charged strut with linear digressive valving. Restores factory ride comfort and steering control.',
    features: ['Gas charged', 'Twin tube design', 'Precision valving', 'Corrosion resistant'],
  },
  {
    id: 'p12',
    name: 'Lower Control Arm Kit (Pair)',
    category: 'suspension',
    brand: 'Kyb',
    partNo: 'KYB SLPA-41',
    price: 4799,
    mrp: 5999,
    stock: 9,
    rating: 4.4,
    reviews: 63,
    popular: false,
    badge: null,
    fits: idsByMake('Honda', 'Toyota', 'Hyundai'),
    desc: 'Pair of complete lower arms with pre-fitted ball joints and bushings. Direct bolt-in replacement, no pressing required.',
    features: ['Pre-fitted ball joints', 'New bushings included', 'Bolt-in fit', 'Sold as pair'],
  },
  {
    id: 'p13',
    name: 'Tie Rod End — Outer (RH)',
    category: 'suspension',
    brand: 'FEBI',
    partNo: 'FEBI 22623',
    price: 699,
    mrp: 899,
    stock: 42,
    rating: 4.5,
    reviews: 51,
    popular: false,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Tata'),
    desc: 'Replacement outer tie rod end with pre-applied thread locking. Restores sharp, stable steering response.',
    features: ['Greased and sealed', 'Thread lock applied', 'OE thread specs', 'Quick fit'],
  },
  {
    id: 'p14',
    name: 'Auxiliary Battery — 45Ah',
    category: 'electrical',
    brand: 'Exide',
    partNo: 'EX 45AH',
    price: 4499,
    mrp: 5499,
    stock: 26,
    rating: 4.7,
    reviews: 198,
    popular: true,
    badge: null,
    fits: fitsAll(),
    desc: 'Maintenance-free flooded battery with calcium grids. Strong cold cranking for reliable starts in all weather.',
    features: ['Maintenance free', 'Calcium grids', '12V 45Ah', '18 month warranty'],
  },
  {
    id: 'p15',
    name: 'LED Headlamp Bulb Kit H4 6000K',
    category: 'electrical',
    brand: 'Hella',
    partNo: 'HELLA 8GA 996 121',
    price: 2199,
    mrp: 2899,
    stock: 0,
    rating: 4.6,
    reviews: 312,
    popular: true,
    badge: 'low',
    fits: fitsAll(),
    desc: 'Canbus-ready H4 LED upgrade with active cooling fan. Crisp 6000K white light with a plug-and-play fitment.',
    features: ['Canbus ready', 'Active cooling', '6000K white', 'Plug and play'],
  },
  {
    id: 'p16',
    name: 'Crankshaft Position Sensor',
    category: 'electrical',
    brand: 'Mahle',
    partNo: 'MAH CS-089',
    price: 1299,
    mrp: 1699,
    stock: 31,
    rating: 4.4,
    reviews: 44,
    popular: false,
    badge: null,
    fits: idsByMake('Hyundai', 'Tata'),
    desc: 'Direct replacement CKP sensor. Fixes starting issues, misfires and erratic idle caused by a failing sensor.',
    features: ['OE electrical spec', 'Sealed connector', 'Direct replacement', 'Quick diagnostics fix'],
  },
  {
    id: 'p17',
    name: 'Radiator Cooling Fan Motor',
    category: 'cooling',
    brand: 'Valeo',
    partNo: 'VAL 757345',
    price: 2599,
    mrp: 3199,
    stock: 14,
    rating: 4.5,
    reviews: 67,
    popular: false,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Honda'),
    desc: 'Balanced fan motor with sealed ball bearings. Restores proper engine cooling at idle and in traffic.',
    features: ['Sealed ball bearings', 'OE mounting', 'Balanced rotor', 'Thermal overload safe'],
  },
  {
    id: 'p18',
    name: 'Engine Coolant Concentrate 1L',
    category: 'cooling',
    brand: 'Bosch',
    partNo: 'BOS COOL-1L',
    price: 449,
    mrp: 599,
    stock: 120,
    rating: 4.7,
    reviews: 224,
    popular: false,
    badge: null,
    fits: fitsAll(),
    desc: 'OAT technology coolant concentrate with corrosion inhibitors. Mixes with all mainstream coolants.',
    features: ['OAT technology', 'Corrosion protection', 'All-season', '1 litre concentrate'],
  },
  {
    id: 'p19',
    name: 'Clutch Kit — Disc, Cover & Bearing',
    category: 'transmission',
    brand: 'Luk',
    partNo: 'LUK 623 3029',
    price: 7299,
    mrp: 8999,
    stock: 8,
    rating: 4.8,
    reviews: 92,
    popular: true,
    badge: 'top',
    fits: idsByMake('Maruti Suzuki', 'Hyundai', 'Honda'),
    desc: 'Full clutch replacement kit. Balanced pressure plate, friction disc and release bearing for smooth engagement.',
    features: ['Disc + cover + bearing', 'Factory balanced', 'Smooth engagement', 'Complete kit'],
  },
  {
    id: 'p20',
    name: 'Gearbox Mount (Engine Support)',
    category: 'transmission',
    brand: 'FEBI',
    partNo: 'FEBI 36498',
    price: 1199,
    mrp: 1499,
    stock: 22,
    rating: 4.3,
    reviews: 38,
    popular: false,
    badge: null,
    fits: idsByMake('Hyundai', 'Mahindra', 'Toyota'),
    desc: 'Hydro-filled transmission mount that kills vibration and clunk from the driveline. Hydraulic damping core.',
    features: ['Hydraulic core', 'Vibration dampening', 'OE fit', 'Direct swap'],
  },
  {
    id: 'p21',
    name: '3D All-Weather Floor Mat Set',
    category: 'care',
    brand: 'TVS',
    partNo: 'TVS MAT-3D',
    price: 1899,
    mrp: 2499,
    stock: 75,
    rating: 4.6,
    reviews: 188,
    popular: true,
    badge: null,
    fits: idsByMake('Maruti Suzuki', 'Hyundai', 'Tata', 'Honda'),
    desc: 'Custom-moulded 3D mats with high walls that contain mud, water and spills. Easy to hose clean.',
    features: ['Custom moulded', 'High walls', 'Anti-skid backing', 'Washable'],
  },
  {
    id: 'p22',
    name: 'Ceramic Coat Paint Sealant 50ml',
    category: 'care',
    brand: 'Valeo',
    partNo: 'VAL CCOAT-50',
    price: 1499,
    mrp: 1999,
    stock: 4,
    rating: 4.5,
    reviews: 96,
    popular: false,
    badge: 'low',
    fits: fitsAll(),
    desc: '9H hardness graphene ceramic coating for a deep gloss and 12 months of hydrophobic protection.',
    features: ['9H hardness', 'Hydrophobic', '12 month durability', 'Easy wipe-on'],
  },
  {
    id: 'p23',
    name: 'Rearview Camera Kit 1080p',
    category: 'care',
    brand: 'Hella',
    partNo: 'HELLA CAM-1080',
    price: 3299,
    mrp: 4099,
    stock: 17,
    rating: 4.7,
    reviews: 143,
    popular: false,
    badge: 'new',
    fits: fitsAll(),
    desc: 'Ultra-wide 170° reverse camera with night vision. IP68 weatherproof and compatible with most head units.',
    features: ['1080p sensor', '170° wide angle', 'IP68 rated', 'Night vision'],
  },
  {
    id: 'p24',
    name: 'Dashcam Front + Rear 4K',
    category: 'care',
    brand: 'Bosch',
    partNo: 'BOS DC4K',
    price: 5999,
    mrp: 7499,
    stock: 12,
    rating: 4.8,
    reviews: 211,
    popular: true,
    badge: 'top',
    fits: fitsAll(),
    desc: 'Dual-channel dashcam with 4K front and 1080p rear recording, GPS logging and parking guard mode.',
    features: ['4K front + 1080p rear', 'GPS logging', 'Parking guard', 'Free 64GB card'],
  },
]

export const preownedProducts = [
  {
    id: 'u1',
    name: 'Front Brake Discs (Pair) · Pre-owned',
    category: 'braking',
    brand: 'Bosch',
    partNo: 'BOS FBD-PO',
    price: 1850,
    mrp: 3890,
    stock: 4,
    rating: 4.6,
    reviews: 87,
    popular: true,
    badge: 'pre',
    condition: 'Excellent',
    km: '12,400 km',
    age: '2019',
    fits: fitsAll(),
    desc: 'Genuine front brake discs removed from a low-mileage car. Checked for thickness, run-out and surface score — ready to fit.',
    features: ['Thickness within spec', 'No scoring or cracks', 'Includes wear inspection', '3-month warranty'],
  },
  {
    id: 'u2',
    name: 'Alternator · Pre-owned',
    category: 'engine',
    brand: 'Valeo',
    partNo: 'VAL ALT-PO',
    price: 2450,
    mrp: 5290,
    stock: 3,
    rating: 4.5,
    reviews: 64,
    popular: false,
    badge: 'pre',
    condition: 'Good',
    km: '31,800 km',
    age: '2017',
    fits: fitsAll(),
    desc: 'Genuine Valeo alternator, load-tested and rebuilt where needed. Output verified against factory spec before dispatch.',
    features: ['Load-tested to spec', 'Bearing & diode check', 'Rebuilt if required', '3-month warranty'],
  },
  {
    id: 'u3',
    name: 'Front Shock Absorber · Pre-owned',
    category: 'suspension',
    brand: 'Monroe',
    partNo: 'MON SHK-PO',
    price: 1550,
    mrp: 3290,
    stock: 5,
    rating: 4.4,
    reviews: 51,
    popular: true,
    badge: 'pre',
    condition: 'Excellent',
    km: '9,600 km',
    age: '2020',
    fits: fitsAll(),
    desc: 'Front shock absorber with no leaks and full rebound. Removed from a car under 10,000 km of use.',
    features: ['No oil leaks', 'Full rebound travel', 'Mounting hardware intact', '3-month warranty'],
  },
  {
    id: 'u4',
    name: 'Starter Motor · Pre-owned',
    category: 'electrical',
    brand: 'Bosch',
    partNo: 'BOS STR-PO',
    price: 2100,
    mrp: 4650,
    stock: 3,
    rating: 4.3,
    reviews: 42,
    popular: false,
    badge: 'pre',
    condition: 'Good',
    km: '27,200 km',
    age: '2018',
    fits: fitsAll(),
    desc: 'Tested starter motor with strong cranking torque. Brushes and solenoid checked before packing.',
    features: ['Cranking test passed', 'Solenoid verified', 'Clean electrical contacts', '3-month warranty'],
  },
  {
    id: 'u5',
    name: 'Radiator · Pre-owned',
    category: 'cooling',
    brand: 'DENSO',
    partNo: 'DEN RAD-PO',
    price: 2850,
    mrp: 6100,
    stock: 2,
    rating: 4.6,
    reviews: 38,
    popular: false,
    badge: 'pre',
    condition: 'Very Good',
    km: '19,400 km',
    age: '2019',
    fits: fitsAll(),
    desc: 'Pressure-tested radiator with no leaks, straight fins and clean core. Coolant flow checked end to end.',
    features: ['Pressure test passed', 'No leaks or repairs', 'Straight fins', '3-month warranty'],
  },
  {
    id: 'u6',
    name: 'Clutch Kit · Pre-owned',
    category: 'transmission',
    brand: 'LUK',
    partNo: 'LUK CLT-PO',
    price: 3450,
    mrp: 7490,
    stock: 3,
    rating: 4.7,
    reviews: 73,
    popular: true,
    badge: 'pre',
    condition: 'Excellent',
    km: '15,100 km',
    age: '2020',
    fits: fitsAll(),
    desc: 'Complete clutch kit with healthy friction plate and diaphragm. Wear depth measured within factory limits.',
    features: ['Friction wear within spec', 'Diaphragm finger height checked', 'Kit complete with release bearing', '3-month warranty'],
  },
  {
    id: 'u7',
    name: 'Air Filter Housing · Pre-owned',
    category: 'filters',
    brand: 'Mahle',
    partNo: 'MHL AFH-PO',
    price: 1450,
    mrp: 2980,
    stock: 6,
    rating: 4.5,
    reviews: 29,
    popular: false,
    badge: 'pre',
    condition: 'Good',
    km: '24,000 km',
    age: '2019',
    fits: fitsAll(),
    desc: 'Genuine air filter housing with intact clips and clean sealing face. Deep cleaned and inspected.',
    features: ['Intact clips & hinge', 'Clean sealing surface', 'Deep cleaned', '3-month warranty'],
  },
  {
    id: 'u8',
    name: 'LED Headlamp Assembly · Pre-owned',
    category: 'care',
    brand: 'Philips',
    partNo: 'PHI HLD-PO',
    price: 2950,
    mrp: 6390,
    stock: 2,
    rating: 4.4,
    reviews: 34,
    popular: false,
    badge: 'pre',
    condition: 'Excellent',
    km: '8,900 km',
    age: '2021',
    fits: fitsAll(),
    desc: 'Low-hour LED headlamp assembly, polished housing and clear lens. Beam pattern and output verified.',
    features: ['Beam output verified', 'Clear, untarnished lens', 'All mounts intact', '3-month warranty'],
  },
]

export const reviews = {
  p1: [
    { id: 'r1a', name: 'Vikram S.', date: '12 Jul 2026', rating: 5, text: 'Perfect fit for my Swift. Ceramic pads are really quiet — no squealing at all. Braking feel is much better than the stock pads.', image: null, verified: true },
    { id: 'r1b', name: 'Priya M.', date: '28 Jun 2026', rating: 4, text: 'Good quality pads. Slight dust reduction compared to old ones. Took about 30 min to install with basic tools.', image: 'https://picsum.photos/seed/r1b/400/300', verified: true },
    { id: 'r1c', name: 'Rahul D.', date: '15 Jun 2026', rating: 5, text: 'Bosch quality as always. These pads grip really well even in wet conditions. Highly recommend for city driving.', image: null, verified: true },
    { id: 'r1d', name: 'Amit K.', date: '3 Jun 2026', rating: 4, text: 'Decent product for the price. My mechanic said the compound looks premium. Will buy again.', image: 'https://picsum.photos/seed/r1d/400/300', verified: false },
  ],
  p2: [
    { id: 'r2a', name: 'Suresh P.', date: '5 Jul 2026', rating: 5, text: 'Excellent rotor. No vibration after installation. Balanced perfectly out of the box.', image: null, verified: true },
    { id: 'r2b', name: 'Deepa R.', date: '20 Jun 2026', rating: 4, text: 'Solid build quality. Bit heavy but that is expected for ventilated discs. Smooth braking now.', image: 'https://picsum.photos/seed/r2b/400/300', verified: true },
    { id: 'r2c', name: 'Karthik N.', date: '8 Jun 2026', rating: 5, text: 'Fitted these on my i20 along with the ceramic pads from here. Night and day difference in stopping power.', image: null, verified: true },
  ],
  p3: [
    { id: 'r3a', name: 'Manoj T.', date: '18 Jul 2026', rating: 5, text: 'Complete kit saved me a lot of hassle. Pads and rotors both in one box. My Baleno brakes feel brand new.', image: 'https://picsum.photos/seed/r3a/400/300', verified: true },
    { id: 'r3b', name: 'Sanjay G.', date: '2 Jul 2026', rating: 5, text: 'Best value kit I found online. Everything you need for a full brake refresh. Workshop charged ₹2000 extra for installation but worth it.', image: null, verified: true },
  ],
  p4: [
    { id: 'r4a', name: 'Neha V.', date: '22 Jul 2026', rating: 5, text: 'The carbon layer really helps with odour. AC smells so much better now. Easy to install — just slides in.', image: null, verified: true },
    { id: 'r4b', name: 'Arjun B.', date: '10 Jul 2026', rating: 4, text: 'Good filter. Noticeably better air quality inside the car. Replacement interval seems reasonable.', image: 'https://picsum.photos/seed/r4b/400/300', verified: true },
    { id: 'r4c', name: 'Riya S.', date: '25 Jun 2026', rating: 5, text: 'Third time buying this. Always consistent quality. My Creta cabin stays dust-free even on bad roads.', image: null, verified: true },
    { id: 'r4d', name: 'Vikash J.', date: '12 Jun 2026', rating: 4, text: 'Decent filter for the price. Fits perfectly in my Venue. Noticed less dust coming through the vents.', image: null, verified: true },
  ],
  p5: [
    { id: 'r5a', name: 'Prakash L.', date: '8 Jul 2026', rating: 5, text: 'Genuine Mann quality. Oil pressure feels consistent. No leaks after installation.', image: null, verified: true },
    { id: 'r5b', name: 'Geeta W.', date: '25 Jun 2026', rating: 4, text: 'Standard spin-on filter. Does its job. Seal gasket is good quality — no seepage.', image: 'https://picsum.photos/seed/r5b/400/300', verified: true },
    { id: 'r5c', name: 'Rajesh F.', date: '10 Jun 2026', rating: 5, text: 'Been using Mann filters for years. Never had an issue. This one fits my Ciaz perfectly.', image: null, verified: true },
  ],
  p6: [
    { id: 'r6a', name: 'Kavita D.', date: '30 Jul 2026', rating: 5, text: 'Perfect fit for my Swift. Noticed better throttle response after replacing the old clogged filter.', image: null, verified: true },
    { id: 'r6b', name: 'Anil M.', date: '15 Jul 2026', rating: 4, text: 'Good panel filter. The mahle quality is evident. Engine breathes easier now.', image: 'https://picsum.photos/seed/r6b/400/300', verified: true },
  ],
  p7: [
    { id: 'r7a', name: 'Tarun K.', date: '20 Jul 2026', rating: 5, text: 'Full synthetic oil changed the way my engine runs. Smoother idle, better mileage. 5L is enough for two services.', image: null, verified: true },
    { id: 'r7b', name: 'Sunita P.', date: '5 Jul 2026', rating: 5, text: 'Excellent oil. My mechanic confirmed it is genuine Motul. Engine feels protected even in stop-go traffic.', image: 'https://picsum.photos/seed/r7b/400/300', verified: true },
    { id: 'r7c', name: 'Vijay R.', date: '18 Jun 2026', rating: 4, text: 'Good synthetic oil but slightly pricey. Performance is there though — smoother shifts and quieter engine.', image: null, verified: true },
  ],
  p8: [
    { id: 'r8a', name: 'Nitin S.', date: '25 Jul 2026', rating: 5, text: 'NGK iridium plugs transformed my i10. Better fuel economy and smoother startup. Set of 4 is perfect.', image: null, verified: true },
    { id: 'r8b', name: 'Pooja H.', date: '12 Jul 2026', rating: 5, text: 'These plugs last way longer than copper ones. Worth the extra cost. Easy to gap and install.', image: 'https://picsum.photos/seed/r8b/400/300', verified: true },
    { id: 'r8c', name: 'Sagar T.', date: '28 Jun 2026', rating: 4, text: 'Good plugs. Noticeable improvement in idle quality. My Baleno runs much smoother now.', image: null, verified: true },
  ],
  p9: [
    { id: 'r9a', name: 'Ramesh C.', date: '15 Jul 2026', rating: 5, text: 'LKQ timing belt kit is complete — belt, tensioner, idler all included. My mechanic said quality is top notch.', image: null, verified: true },
    { id: 'r9b', name: 'Meena J.', date: '1 Jul 2026', rating: 5, text: 'Installed at 80k km as preventive. Kit includes everything. Belt tension is holding perfectly.', image: 'https://picsum.photos/seed/r9b/400/300', verified: true },
  ],
  p10: [
    { id: 'r10a', name: 'Ashok V.', date: '8 Jul 2026', rating: 4, text: 'Good drive belt. Fits my Verna perfectly. No squealing on cold starts anymore.', image: null, verified: true },
    { id: 'r10b', name: 'Divya N.', date: '22 Jun 2026', rating: 5, text: 'Contitech belt — OEM quality at a much better price. Replaced at 60k km. Smooth and quiet.', image: null, verified: true },
  ],
  p11: [
    { id: 'r11a', name: 'Pradeep R.', date: '10 Jul 2026', rating: 5, text: 'Monroe gas shocks are excellent. Ride quality improved dramatically. No more bouncing over bumps.', image: 'https://picsum.photos/seed/r11a/400/300', verified: true },
    { id: 'r11b', name: 'Lakshmi B.', date: '25 Jun 2026', rating: 4, text: 'Good shock absorber. Stiff but controlled ride. Feels much more planted at highway speeds.', image: null, verified: true },
    { id: 'r11c', name: 'Ganesh K.', date: '8 Jun 2026', rating: 5, text: 'Replaced both fronts. Car feels like new. Monroe never disappoints. Highly recommend for i20 owners.', image: null, verified: true },
  ],
  p12: [
    { id: 'r12a', name: 'Sunil M.', date: '3 Jul 2026', rating: 5, text: 'KYB control arms are solid. Pair pricing is great. No more clunking noise from the front suspension.', image: null, verified: true },
    { id: 'r12b', name: 'Priti S.', date: '18 Jun 2026', rating: 4, text: 'Good quality arms. Boot and ball joint came pre-assembled. Saved a trip to the press shop.', image: 'https://picsum.photos/seed/r12b/400/300', verified: true },
  ],
  p13: [
    { id: 'r13a', name: 'Vinod T.', date: '28 Jul 2026', rating: 5, text: 'Perfect fit for my City. Steering feels tight and responsive again. No play at all after installation.', image: null, verified: true },
    { id: 'r13b', name: 'Aarti G.', date: '12 Jul 2026', rating: 4, text: 'Decent tie rod end. Thread quality is good. Slight grease leakage after a month but nothing major.', image: null, verified: true },
  ],
  p14: [
    { id: 'r14a', name: 'Dinesh P.', date: '20 Jul 2026', rating: 5, text: 'Exide battery — reliable as always. Cranks strong even in summer. 3-year warranty is a plus.', image: 'https://picsum.photos/seed/r14a/400/300', verified: true },
    { id: 'r14b', name: 'Kamini R.', date: '5 Jul 2026', rating: 5, text: 'Good battery for the price. My Swift starts instantly now. Delivery was quick and well-packed.', image: null, verified: true },
    { id: 'r14c', name: 'Harish L.', date: '18 Jun 2026', rating: 4, text: 'Solid 45Ah battery. Slightly heavier than the stock one but fits the tray fine. Good value.', image: null, verified: true },
  ],
  p15: [
    { id: 'r15a', name: 'Rohit J.', date: '15 Jul 2026', rating: 5, text: 'These LEDs are incredibly bright. 6000K white light is perfect. Night driving is so much safer now.', image: 'https://picsum.photos/seed/r15a/400/300', verified: true },
    { id: 'r15b', name: 'Swati D.', date: '28 Jun 2026', rating: 5, text: 'Plug and play H4 fitment. No error codes on my dashboard. Light output is excellent.', image: null, verified: true },
    { id: 'r15c', name: 'Yash P.', date: '10 Jun 2026', rating: 4, text: 'Bright LEDs but run slightly warm. Need to make sure the heatsink clears the dust cover. Otherwise great.', image: null, verified: true },
  ],
  p16: [
    { id: 'r16a', name: 'Sanjay K.', date: '5 Jul 2026', rating: 5, text: 'Fixed my check engine light. OEM Bosch sensor, works perfectly. Idle is smooth again.', image: null, verified: true },
    { id: 'r16b', name: 'Anita V.', date: '20 Jun 2026', rating: 4, text: 'Good sensor. Connector fits snugly. Had to clear the ECU codes manually but after that runs great.', image: 'https://picsum.photos/seed/r16b/400/300', verified: true },
  ],
  p17: [
    { id: 'r17a', name: 'Ajay N.', date: '12 Jul 2026', rating: 5, text: 'Fan motor is powerful and quiet. Replaced my noisy old one. Cooling performance is back to normal.', image: null, verified: true },
    { id: 'r17b', name: 'Nisha M.', date: '28 Jun 2026', rating: 4, text: 'Good motor. Slightly different mounting bracket but adapter included. Works fine on my EcoSport.', image: null, verified: true },
  ],
  p18: [
    { id: 'r18a', name: 'Arun S.', date: '22 Jul 2026', rating: 5, text: 'Bosch coolant concentrate — mix with distilled water and you are set. Engine temperature is stable even in traffic.', image: 'https://picsum.photos/seed/r18a/400/300', verified: true },
    { id: 'r18b', name: 'Rekha P.', date: '8 Jul 2026', rating: 5, text: 'Good coolant. Green colour makes it easy to check levels. No corrosion deposits visible after 6 months.', image: null, verified: true },
    { id: 'r18c', name: 'Kiran B.', date: '20 Jun 2026', rating: 4, text: 'Decent coolant for the price. 1L is enough for a top-up. Used 2 bottles for a full flush on my Swift.', image: null, verified: true },
  ],
  p19: [
    { id: 'r19a', name: 'Mahesh G.', date: '10 Jul 2026', rating: 5, text: 'Complete Luk clutch kit — disc, cover and bearing all in one. Pedal feel is smooth and engagement point is perfect.', image: null, verified: true },
    { id: 'r19b', name: 'Savita L.', date: '25 Jun 2026', rating: 5, text: 'My Alto drives like new after clutch replacement. Luk quality is outstanding. Mechanic praised the kit.', image: 'https://picsum.photos/seed/r19b/400/300', verified: true },
  ],
  p20: [
    { id: 'r20a', name: 'Prakash D.', date: '3 Jul 2026', rating: 4, text: 'Good gearbox mount. Reduced vibrations noticeably. Installation was straightforward.', image: null, verified: true },
    { id: 'r20b', name: 'Sneha R.', date: '18 Jun 2026', rating: 5, text: 'Solid rubber mount. Engine noise dropped significantly. Worth replacing when doing timing belt.', image: null, verified: true },
  ],
  p21: [
    { id: 'r21a', name: 'Rajiv T.', date: '28 Jul 2026', rating: 5, text: 'These floor mats are amazing. 3D design catches all the mud and water. Fits my Creta perfectly.', image: 'https://picsum.photos/seed/r21a/400/300', verified: true },
    { id: 'r21b', name: 'Pallavi M.', date: '15 Jul 2026', rating: 5, text: 'Best floor mats I have owned. Easy to clean — just hose them down. No more dirty carpets.', image: null, verified: true },
    { id: 'r21c', name: 'Umesh K.', date: '2 Jul 2026', rating: 4, text: 'Good mats but slightly expensive. Build quality is premium though. Should last years.', image: null, verified: true },
    { id: 'r21d', name: 'Tanvi S.', date: '18 Jun 2026', rating: 5, text: 'Perfect fit, no sliding around. The raised edges keep all the water contained. Love them.', image: null, verified: true },
  ],
  p22: [
    { id: 'r22a', name: 'Sachin P.', date: '20 Jul 2026', rating: 5, text: 'Applied ceramic coat on my i20. Water beading is incredible. Paint looks glossy and protected.', image: 'https://picsum.photos/seed/r22a/400/300', verified: true },
    { id: 'r22b', name: 'Megha J.', date: '5 Jul 2026', rating: 4, text: 'Good sealant but requires careful application. Followed the instructions and got great results.', image: null, verified: true },
  ],
  p23: [
    { id: 'r23a', name: 'Naveen R.', date: '15 Jul 2026', rating: 5, text: 'Crystal clear 1080p feed. Night vision is surprisingly good. Wide angle covers the whole rear bumper.', image: null, verified: true },
    { id: 'r23b', name: 'Deepti A.', date: '1 Jul 2026', rating: 5, text: 'Installation was easy with the included cables. Display on my head unit is sharp. Great for parking.', image: 'https://picsum.photos/seed/r23b/400/300', verified: true },
    { id: 'r23c', name: 'Varun N.', date: '20 Jun 2026', rating: 4, text: 'Good camera for the price. Waterproof rating works in monsoon. Slight fish-eye but acceptable.', image: null, verified: true },
  ],
  p24: [
    { id: 'r24a', name: 'Ishaan K.', date: '25 Jul 2026', rating: 5, text: 'Front and rear 4K dashcam — the video quality is stunning. Caught a minor fender bender on video already.', image: null, verified: true },
    { id: 'r24b', name: 'Rohini S.', date: '10 Jul 2026', rating: 5, text: 'Excellent dashcam setup. Parking mode works great. App connectivity makes it easy to download clips.', image: 'https://picsum.photos/seed/r24b/400/300', verified: true },
    { id: 'r24c', name: 'Gaurav T.', date: '22 Jun 2026', rating: 4, text: 'Good dashcam but needs a hardwire kit for parking mode. Video quality in 4K is really impressive though.', image: null, verified: true },
  ],
  u1: [
    { id: 'ru1a', name: 'Keshav M.', date: '18 Jul 2026', rating: 4, text: 'Excellent condition for a pre-owned part. No runout, no scoring. Works perfectly on my 2019 Baleno.', image: 'https://picsum.photos/seed/ru1a/400/300', verified: true },
    { id: 'ru1b', name: 'Sumita D.', date: '3 Jul 2026', rating: 5, text: 'Saved a lot compared to new discs. Surface is smooth and balanced. Great value pre-owned part.', image: null, verified: true },
  ],
  u2: [
    { id: 'ru2a', name: 'Abhishek R.', date: '10 Jul 2026', rating: 4, text: 'Alternator tested fine. Putting out 14.2V as expected. Good condition for 31k km usage.', image: null, verified: true },
    { id: 'ru2b', name: 'Pavitra L.', date: '25 Jun 2026', rating: 3, text: 'Works but shows minor cosmetic wear. Electrical output is fine though. Acceptable for the price.', image: 'https://picsum.photos/seed/ru2b/400/300', verified: true },
  ],
  u3: [
    { id: 'ru3a', name: 'Tarun V.', date: '22 Jul 2026', rating: 5, text: 'Excellent condition shock. Gas pressure is strong. No leaks at all. Feels almost new on my Swift.', image: null, verified: true },
  ],
  u4: [
    { id: 'ru4a', name: 'Mohan K.', date: '5 Jul 2026', rating: 4, text: 'Starter motor engages strongly. Minor paint wear but functionally perfect. Good pre-owned deal.', image: null, verified: true },
    { id: 'ru4b', name: 'Lata P.', date: '20 Jun 2026', rating: 4, text: 'Works well on my i10. Quick cranking. A bit dirty externally but cleaned up fine.', image: 'https://picsum.photos/seed/ru4b/400/300', verified: true },
  ],
  u5: [
    { id: 'ru5a', name: 'Hitesh J.', date: '15 Jul 2026', rating: 4, text: 'Radiator in very good condition. No leaks in any rows. Core is clean. Good replacement part.', image: null, verified: true },
  ],
  u6: [
    { id: 'ru6a', name: 'Sanjay N.', date: '8 Jul 2026', rating: 5, text: 'Excellent condition clutch kit. Disc thickness is well within spec. Pressure plate springs are strong.', image: null, verified: true },
    { id: 'ru6b', name: 'Renuka S.', date: '22 Jun 2026', rating: 4, text: 'Good pre-owned clutch. Bearing is quiet. Disc has plenty of life left. Saved almost 60% vs new.', image: 'https://picsum.photos/seed/ru6b/400/300', verified: true },
  ],
  u7: [
    { id: 'ru7a', name: 'Venu G.', date: '12 Jul 2026', rating: 3, text: 'Filter housing is intact but a bit dusty. Clips are fine. Works as expected on my Venue.', image: null, verified: true },
  ],
  u8: [
    { id: 'ru8a', name: 'Rakesh B.', date: '20 Jul 2026', rating: 5, text: 'LED headlamp assembly in excellent condition. All LEDs work perfectly. Great deal for a pre-owned part.', image: null, verified: true },
    { id: 'ru8b', name: 'Shruti K.', date: '5 Jul 2026', rating: 4, text: 'Good headlamp assembly. Minor scratch on the housing but lens is clear. Light output is perfect.', image: 'https://picsum.photos/seed/ru8b/400/300', verified: true },
  ],
}

export const testimonials = [
  {
    name: 'Rakesh Mehta',
    role: 'Owner, Mehta Motors & Auto Garage',
    city: 'Pune',
    quote:
      'We switched our whole workshop to Assemble-on-line for B2B ordering. Part numbers always match, delivery is next-day and the pricing is unbeatable.',
  },
  {
    name: 'Anjali Sharma',
    role: 'Car owner — Hyundai i20',
    city: 'Mumbai',
    quote:
      'Picked my exact brake pads using the fitment finder in under a minute. Genuine Bosch pads, delivered in two days. Amazing.',
  },
  {
    name: 'Suresh Nair',
    role: 'Fleet manager, 40+ vehicles',
    city: 'Bengaluru',
    quote:
      'Ordering bulk filters and service parts for our fleet is now one workflow. GST invoices, accurate stock, zero wrong parts so far.',
  },
]

export const stats = [
  { value: '22,000+', label: 'Live SKUs' },
  { value: '1,800+', label: 'Partner workshops' },
  { value: '12 hrs', label: 'Metro delivery' },
  { value: '100%', label: 'Genuine parts' },
]

export function formatINR(n) {
  return '₹' + n.toLocaleString('en-IN')
}

export const interchanges = [
  { oem: 'OEM 4514951H10', partNo: '0 986 AB1 238', brand: 'Bosch', note: 'Front disc brake pads' },
  { oem: 'OEM 58101-0X020', partNo: '0 986 AB1 238', brand: 'Bosch', note: 'Front disc brake pads' },
  { oem: 'OEM 16510-21040', partNo: 'W 712/22', brand: 'Mann-Filter', note: 'Engine oil filter' },
  { oem: 'OEM 17801-21060', partNo: 'LX 1768', brand: 'Mahle', note: 'Panel air filter' },
  { oem: 'OEM 9807B-56106', partNo: 'NGK 96312', brand: 'NGK', note: 'Iridium spark plugs' },
  { oem: 'OEM 18821-21060', partNo: 'CUK 2434', brand: 'Mann-Filter', note: 'Carbon cabin filter' },
  { oem: 'OEM 54610-0X020', partNo: 'G16551', brand: 'Monroe', note: 'Front shock absorber' },
  { oem: 'OEM 54500-0X020', partNo: 'KYB SLPA-41', brand: 'Kyb', note: 'Lower control arm pair' },
  { oem: 'OEM 12100-21060', partNo: 'LUK 534 0103', brand: 'Luk', note: 'Timing belt kit' },
  { oem: 'OEM 31110-21060', partNo: 'EX 45AH', brand: 'Exide', note: 'Auxiliary battery' },
  { oem: 'OEM 31250-12120', partNo: 'BOS COOL-1L', brand: 'Bosch', note: 'Engine coolant' },
  { oem: 'OEM 21010-61K00', partNo: 'LUK 623 3029', brand: 'Luk', note: 'Clutch kit' },
  { oem: 'OEM 91700-21060', partNo: 'HELLA 8GA 996 121', brand: 'Hella', note: 'H4 LED headlamp kit' },
]

export function interchangesFor(partNo) {
  return interchanges.filter((i) => i.partNo === partNo)
}

export function findInterchanges(term) {
  const q = String(term || '').trim().toLowerCase()
  if (!q) return []
  return interchanges.filter(
    (i) => i.partNo.toLowerCase().includes(q) || i.oem.toLowerCase().includes(q),
  )
}

export function getProduct(id) {
  return (
    products.find((p) => p.id === id) ||
    preownedProducts.find((p) => p.id === id)
  )
}

export function getCategory(id) {
  return categories.find((c) => c.id === id)
}
